# 4.R — author-annotation recoding with explicit tissue provenance
# Reads the object generated by 3.R; no missing intermediate annotation script is required.
.file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
.script_dir <- if (length(.file_arg)) dirname(normalizePath(sub("^--file=", "", .file_arg[1]), mustWork = FALSE)) else getwd()
source(file.path(.script_dir, "config.R"))
require_packages(c("Seurat", "ggplot2", "dplyr"))

out_dir <- ensure_dir(project_path("02_scRNA_analysis", "GSE132465_corrected"))
table_dir <- ensure_dir(project_path("08_tables", "GSE132465_corrected", "annotation"))
fig_dir <- ensure_dir(project_path("07_figures", "GSE132465_corrected", "annotation"))
seu <- readRDS(file.path(out_dir, "GSE132465_SCT_clustered_seurat.rds"))
required <- c("condition", "Sample", "Patient", "Cell_type", "Cell_subtype")
if (length(setdiff(required, colnames(seu@meta.data))) > 0) stop("Required author metadata is missing.")

seu$major_celltype <- "Other"
seu$major_celltype[seu$Cell_type == "Epithelial cells"] <- "Epithelial"
seu$major_celltype[seu$Cell_type == "Myeloids"] <- "Myeloid"
seu$major_celltype[seu$Cell_type == "T cells"] <- "T_NK"
seu$major_celltype[seu$Cell_type == "B cells"] <- "B_Plasma"
seu$major_celltype[seu$Cell_type == "Mast cells"] <- "Mast"
seu$major_celltype[seu$Cell_subtype %in% c("Myofibroblasts", "Stromal 1", "Stromal 2", "Stromal 3")] <- "Fibroblast_stromal"
seu$major_celltype[seu$Cell_subtype %in% c("Stalk-like ECs", "Tip-like ECs", "Lymphatic ECs", "Proliferative ECs")] <- "Endothelial"
seu$major_celltype[seu$Cell_subtype == "Pericytes"] <- "Pericyte"
seu$major_celltype[seu$Cell_subtype == "Smooth muscle cells"] <- "Smooth_muscle"
seu$major_celltype[seu$Cell_subtype == "Enteric glial cells"] <- "Enteric_glial"
seu$epithelial_provenance <- ifelse(
  seu$major_celltype == "Epithelial", paste0(seu$condition, "_tissue_epithelial"), "Non_epithelial"
)

# This is specimen provenance, not a malignant-cell call.
seu$malignant_status_proven <- FALSE
write_csv_atomic(as.data.frame(table(seu$major_celltype, seu$condition)), file.path(table_dir, "major_celltype_by_condition.csv"))
write_csv_atomic(as.data.frame(table(seu$Cell_subtype, seu$condition)), file.path(table_dir, "subtype_by_condition.csv"))
p <- Seurat::DimPlot(seu, reduction = "umap", group.by = "major_celltype", label = TRUE, repel = TRUE)
ggplot2::ggsave(file.path(fig_dir, "UMAP_major_celltype.pdf"), p, width = 9, height = 7)
saveRDS(seu, file.path(out_dir, "GSE132465_author_annotated_corrected.rds"))
